<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div>
    <form method="post">
        <input type="text" name="firstName" placeholder="Имя">
        <br>
        <input type="text" name="lastName" placeholder="Фамилия">
        <br>
        <input type="text" name="age" placeholder="Возраст">
        <br>
        <input type="text" name="login" placeholder="Логин">
        <br>
        <input type="text" name="passwordHash" placeholder="Пароль">
        <br>
        <input type="submit" value="ОК">
    </form>
</div>
</body>
</html>